### ISSUE TITLE
Update README with Windows commands

### ISSUE THREAD

**Issue by pongloongyeat** [pongloongyeat/villager-bot#22]

**Comment by ishanpan** [comment]
Should I also include on how to install python 3 on windows in updated readme?

**Comment by pongloongyeat** [comment]
Hey, after some thought I think the only Windows-specific command that needs updating is on how to activate a virtual environment. I'll toss the install stuff in the Wiki instead :)

**Comment by 96RadhikaJadhav** [comment]
@pongloongyeat  Can I add commands in README on how to activate a virtual environment?

**Comment by pongloongyeat** [comment]
Yes you can! Just submit a PR with changes to the README

**Comment by pongloongyeat** [comment]
Closed via #29
